# Generated by Django 3.2 on 2022-05-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('capsule_id', models.IntegerField(blank=True, null=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('mobile_number', models.PositiveIntegerField(blank=True, null=True)),
                ('battery_percentage', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capsule',
            },
        ),
        migrations.CreateModel(
            name='CapsuleDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.CharField(blank=True, max_length=30, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('physical_device', models.BooleanField(blank=True, default=False, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capsuledetails',
            },
        ),
    ]
