# Generated by Django 3.2 on 2022-05-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextFruit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='mobile_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
