# Generated by Django 3.2 on 2022-05-16 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NextFruit', '0003_alter_capsule_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='mobile_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e098c422-3cbc-4ae5-b60d-f841dda04ed1'), primary_key=True, serialize=False),
        ),
    ]
