# Generated by Django 3.2 on 2022-05-17 04:49

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('NextFruit', '0006_alter_capsule_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='capsule',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='capsule',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
